title: 레이븐코인
author: RavenProject
description: 레이븐코인은 효율적인 자산 생성 및 전송을 위한 피어투피어 블록체인이며, 비트코인 코드를 포크한 오픈소스 프로젝트입니다.

baseurl: ""

# social links
twitter_username: ravencoin
github_username:  RavenProject
rss: rss

show_excerpts: false

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - _pages/index.md
 - _pages/buy-ravencoin.md
 - _pages/wallet.md
 - _pages/whitepaper.md
 - _pages/community.md
 - _pages/pools.md

# Build settings
theme: minima
relative_permalinks: false

# Reading Files
include:
  - _pages
  - _posts
  - _wallets
  - _translations

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default

plugins:
 - jekyll-feed
 - jekyll-seo-tag
